name: crawler_latest_urls
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 1,15 * *"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: run script
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CODING_TOKEN: ${{ secrets.CODING_TOKEN }}
        run: |
          node crawler_latest_urls.js
      - name: Commit
        run: |
          git config --global user.email example@example.com
          git config --global user.name example
          git add .
          git commit -m"`date +'%Y-%m-%d'` crawler latest urls"
          git pull --rebase

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
